### ISSUE TITLE
Källa för overfitting saknas

### ISSUE THREAD

**Issue by macaullyjames** [macaullyjames/bachelor-thesis#1]
Från avsnittet "Support vector machines":

> There is a balance in how much data the algorithm should have. Using
> too much information can lead to “overfitting” and the algorithm will perform
> poorer for new data (TK: Weston, n.d.).

Hittar inte Weston bland källorna, vet du vad som menas här @johanwik? :)

**Comment by johanwik** [comment]
http://www.cs.columbia.edu/~kathy/cs4701/documents/jason_svm_tutorial.pdf är källan... har för mig jag lade till den men kanske försvann

**Comment by johanwik** [comment]
Weston, J. n.d. Support Vector Machine (and Statistical Learning Theory) 
Tutorial URL: http://www.cs.columbia.edu/~kathy/cs4701/documents/jason_svm_tutorial.pdf fanns i driveversionen
